name: NPM Audit Scan using Github Actions

on:
  push:
    branches: [ master]
  workflow_dispatch:

jobs:
  npm-audit-scan-job:
    name: NPM Audit Scan for Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Step1 Download the Source Code
        uses: actions/checkout@v3.5.3

      - name: Step2 Install Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: '18.16.1'

      - name: Step3 Install Dependencies
        run: npm install

      - name: Step4 NPM Audit Scan and Generate Report in JSON Format
        run: npm audit --json > npm-audit-results.json
        continue-on-error: true

      - name: Step5 Upload NPM Audit Scan Report to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: npm-audit-results
          path: npm-audit-results.json